# Site settings
title: Farhan Mufti Hilmy's CV 
description: Farhan Mufti Hilmy's CV
favicon: /assets/img/avatar.JPG
baseurl: 
url: https://rechitofficial.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Farhan Mufti Hilmy
  title: Mobile Developer
  address: Yogyakarta, Indonesia
  email: farhanmuftihilmy@gmail.com
  link: http://ddbullfrog.com
  weibo:
  github: rechitofficial
  linkedin: rechitofficial
  twitter: rechitofficial
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: XXX Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: Gadjah Mada University
      location: Yogyakarta, Indonesia
      degree: D4
      major: Software Engineering
      started: 2019
      duration: (2019 - Now)
      description: 
    - education2:
      organization: Senior High School 1 of Kebumen
      location: Central Java, Indonesia
      degree: 
      major: Mathematics, Science
      started: 2016
      duration: (2016 - 2019)
      description: 
    - education3:
      organization: Junior High School 1 of Kebumen
      location: Central Java, Indonesia
      degree: 
      major: Mathematics, Science, Civics, English, Indonesian, Religious Study
      started: 2013
      duration: (2013 - 2016)
      description: 
  languages:
    - language1:
      name: Indonesia
      proficiency: Native
    - language2:
      name: English
      proficiency: Intermediate
    - language3:
      name: Arabic
      proficiency: Novice  
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%
